game_preferences:

  teams_amount: 4
  players_per_team: 4

magic_cores_types: "level_1;level_2;level_3"

magic_cores:
  level_1:
    manaPerTick: 1
    radius: 10
  level_2:
    manaPerTick: 5
    radius: 7
  level_3:
    manaPerTick: 10
    radius: 4







